/// Activity type dimension describing the type of activity (feeding style and diet focus)
table Activity
	lineageTag: a146fd19-4317-4879-90be-d1778529d32c

	/// Primary key for the Activity dimension
	column Activity_Type_Key
		dataType: int64
		isKey
		formatString: 0
		lineageTag: ad7a831e-3b42-421f-84b5-19ef349e6d26
		summarizeBy: none
		sourceColumn: Activity_Type_Key

		annotation SummarizationSetBy = Automatic

	/// Description of the activity type
	column Activity_Description
		dataType: string
		lineageTag: ab3ae784-4fe5-4474-8c6a-682234044a4d
		summarizeBy: none
		sourceColumn: Activity_Description

		annotation SummarizationSetBy = Automatic

	/// Style of feeding behavior (e.g. stalking, foraging)
	column Feeding_Style
		dataType: string
		lineageTag: a80c6229-55f6-49d9-aeb1-2bd78b8ee8fd
		summarizeBy: none
		sourceColumn: Feeding_Style

		annotation SummarizationSetBy = Automatic

	/// Primary dietary focus of the activity
	column Primary_Diet_Focus
		dataType: string
		lineageTag: adf344f0-aa4f-462d-9dcd-f6c30886f808
		summarizeBy: none
		sourceColumn: Primary_Diet_Focus

		annotation SummarizationSetBy = Automatic

	partition activity = m
		mode: import
		source =
				let
				    Quelle = Csv.Document(File.Contents("C:\Users\domin\Documents\Power BI Modelling MCP Server\Third Project\SwissAnimals\Activity.csv"),[Delimiter=",", Columns=4, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Höher gestufte Header" = Table.PromoteHeaders(Quelle, [PromoteAllScalars=true]),
				    #"Geänderter Typ" = Table.TransformColumnTypes(#"Höher gestufte Header",{{"Activity_Type_Key", Int64.Type}, {"Activity_Description", type text}, {"Feeding_Style", type text}, {"Primary_Diet_Focus", type text}})
				in
				    #"Geänderter Typ"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

